// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTom2eGYB_20sP2Wiob1UGJcklfA9VT_8',
    appId: '1:913375873486:web:4988d4d337b1ac4b51039f',
    messagingSenderId: '913375873486',
    projectId: 'prosen-8df1f',
    authDomain: 'prosen-8df1f.firebaseapp.com',
    storageBucket: 'prosen-8df1f.appspot.com',
    measurementId: 'G-BGTS10MS2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyaFCAsTHoeoAWYMIqmwdO3eO202l4rew',
    appId: '1:913375873486:android:1eef94c288a1e6ef51039f',
    messagingSenderId: '913375873486',
    projectId: 'prosen-8df1f',
    storageBucket: 'prosen-8df1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkW_3Ct1NWzskB11i2bZfxj--rWNRiTu8',
    appId: '1:913375873486:ios:0730b89790a15f5951039f',
    messagingSenderId: '913375873486',
    projectId: 'prosen-8df1f',
    storageBucket: 'prosen-8df1f.appspot.com',
    iosBundleId: 'com.example.prosen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjQuBruG8pq8uQDGC6q4BMFHcQrZWegKc',
    appId: '1:1043561267868:ios:6c6970b77c9d042cd12359',
    messagingSenderId: '1043561267868',
    projectId: 'tutorial-28cba',
    storageBucket: 'tutorial-28cba.appspot.com',
    iosBundleId: 'com.example.tooo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6oZbxK1mH_xg3UOQ82e7ihRpVJaLY-_I',
    appId: '1:1043561267868:web:4ec5619fa1e45bb5d12359',
    messagingSenderId: '1043561267868',
    projectId: 'tutorial-28cba',
    authDomain: 'tutorial-28cba.firebaseapp.com',
    storageBucket: 'tutorial-28cba.appspot.com',
  );
}